# Generated by Django 3.0.14 on 2022-03-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='Notification',
        ),
    ]
