# Generated by Django 3.0.14 on 2022-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220329_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
