# Generated by Django 3.0.14 on 2022-03-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220330_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='companies_worked_in',
            field=models.TextField(default='nil', max_length=200),
        ),
    ]
