# Generated by Django 3.0.14 on 2022-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220330_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_details',
            field=models.TextField(default='nil', max_length=300),
        ),
    ]
