# Generated by Django 3.0.14 on 2022-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_company_job_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_user_id', models.CharField(max_length=20)),
                ('comp_user_id', models.CharField(max_length=20)),
                ('app_title', models.CharField(max_length=20)),
                ('application', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='job_details',
            field=models.TextField(default='nil', max_length=500),
        ),
    ]
