# Generated by Django 4.0.3 on 2022-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220330_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_path',
            field=models.CharField(default='nil', max_length=100),
        ),
    ]
