# Generated by Django 4.0.3 on 2022-04-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='Resumes'),
        ),
    ]
