# Generated by Django 4.0.3 on 2022-04-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_student_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_to_Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alum_uid', models.CharField(max_length=30)),
                ('comp_uid', models.CharField(max_length=30)),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
